const checkboxData = {
  formId: "checkboxData",
  checkboxField: {
    firstCheckbox: {
      position: "1",
      text: "¿Cómo se administra la planificación en tu empresa en general?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Se planifica mensualmente las ventas.",
      labelCheckbox2: "Se planifica anualmente las ventas.",
      labelCheckbox3: "Se planifica anualmente los ingresos y los egresos.",
      labelCheckbox4: "Se elabora un presupuesto económico y financiero.",
      labelCheckbox5:
        "Se elabora un plan estratégico de mediano/largo plazo y un presupuesto económico financiero.",
    },
    secondCheckbox: {
      position: "2",
      text: "¿Cómo definirías el grado de madurez del equipo en el proceso de toma de decisiones?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Contrata algunas personas para tareas operativas.",
      labelCheckbox2:
        "Trabaja con colaboradores pero se reservan todas las decisiones.",
      labelCheckbox3: "Delega algunas decisiones a empleados de confianza.",
      labelCheckbox4:
        "Incorpora empleados experimentados y profesionales con los que se comparte la toma de decisiones.",
      labelCheckbox5:
        "Profesionaliza la operación de la empresa y la dirección se dedica a definir objetivos y monitorear su cumplimiento.",
    },
    thirdCheckbox: {
      position: "1",
      text: "¿Cómo se administra la planificación en tu empresa en general?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Se planifica mensualmente las ventas.",
      labelCheckbox2: "Se planifica anualmente las ventas.",
      labelCheckbox3: "Se planifica anualmente los ingresos y los egresos.",
      labelCheckbox4: "Se elabora un presupuesto económico y financiero.",
      labelCheckbox5:
        "Se elabora un plan estratégico de mediano/largo plazo y un presupuesto económico financiero.",
    },
    fourthCheckbox: {
      position: "1",
      text: "¿Cómo se administra la planificación en tu empresa en general?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Se planifica mensualmente las ventas.",
      labelCheckbox2: "Se planifica anualmente las ventas.",
      labelCheckbox3: "Se planifica anualmente los ingresos y los egresos.",
      labelCheckbox4: "Se elabora un presupuesto económico y financiero.",
      labelCheckbox5:
        "Se elabora un plan estratégico de mediano/largo plazo y un presupuesto económico financiero.",
    },
    fifthCheckbox: {
      position: "1",
      text: "¿Cómo se administra la planificación en tu empresa en general?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Se planifica mensualmente las ventas.",
      labelCheckbox2: "Se planifica anualmente las ventas.",
      labelCheckbox3: "Se planifica anualmente los ingresos y los egresos.",
      labelCheckbox4: "Se elabora un presupuesto económico y financiero.",
      labelCheckbox5:
        "Se elabora un plan estratégico de mediano/largo plazo y un presupuesto económico financiero.",
    },
    sixthCheckbox: {
      position: "1",
      text: "¿Cómo se administra la planificación en tu empresa en general?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Se planifica mensualmente las ventas.",
      labelCheckbox2: "Se planifica anualmente las ventas.",
      labelCheckbox3: "Se planifica anualmente los ingresos y los egresos.",
      labelCheckbox4: "Se elabora un presupuesto económico y financiero.",
      labelCheckbox5:
        "Se elabora un plan estratégico de mediano/largo plazo y un presupuesto económico financiero.",
    },
    seventhCheckbox: {
      position: "1",
      text: "¿Cómo se administra la planificación en tu empresa en general?",
      name1: "monthlyPlanning",
      name2: "annualPlanification",
      name3: "annualPlanificationIncomeExpenses",
      name4: "economicAndFinancialBudget",
      name5: "strategicPlan",
      labelCheckbox1: "Se planifica mensualmente las ventas.",
      labelCheckbox2: "Se planifica anualmente las ventas.",
      labelCheckbox3: "Se planifica anualmente los ingresos y los egresos.",
      labelCheckbox4: "Se elabora un presupuesto económico y financiero.",
      labelCheckbox5:
        "Se elabora un plan estratégico de mediano/largo plazo y un presupuesto económico financiero.",
    },
  },
};

export default checkboxData;
